data:
  raw: "data/raw/BankChurners.csv"
  processed: "data/preprocess/processed_data.csv"

model:
  type: "ExtraTreesClassifier"
  random_state: 42
  top_k_features: 10

training:
  test_size: 0.3
  smote_random_state: 42
  model_save_path: "model"

evaluation:
  save_path: "evaluation"
  metrics:
    - "accuracy"
    - "classification_report"
