version : "3.7"

services:
  minio:
    image:  minio/minio:latest
    container_name: minio
    environment:
       MINIO_ACCESS_KEY : admin123
       MINIO_SECRET_KEY : admin123
    ports:
      - "9000:9000" # api , web ui
      - "9001:9001" # console ui
    volumes:
      - minio_data:/data
    command : server /data
    restart : always

  ml-pipeline:
    build: 
      context: .
    container_name: ml-pipeline
    environment:
       MINIO_ACCESS_KEY : admin123
       MINIO_SECRET_KEY : admin123
       MINIO_URL : http:/minio:9000
    depends_on:
      - minio
    volumes:
      - .:/app
    command: ["bash", "-c", "dvc pull && python scripts/data_preprocess.py && python scripts/model_train.py && python scripts/model_evaluation.py"]

volumes:
  minio_data:
    driver: local
