name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pytest tests/

    - name: Build Docker image
      run: |
        docker build -t customer-churn-mlops:latest .

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      run: |
        echo $DOCKER_HUB_ACCESS_TOKEN | docker login -u $DOCKER_HUB_USERNAME --password-stdin
        docker tag customer-churn-mlops:latest $DOCKER_HUB_USERNAME/customer-churn-mlops:latest
        docker push $DOCKER_HUB_USERNAME/customer-churn-mlops:latest
    
    - name: Verify Docker installation
      run: docker --version

    # - name: Deploy to Server
    #   run: |
    #     # Add deployment commands here (e.g., Kubernetes or Docker Compose)